name: Vérification site HTML-CSS

on: [push]

jobs:
  verification:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Vérifier le site
        run: echo "Site HTML/CSS OK ✅"
